// Document Object Model(DOM);
// Application Programming Interface(API);
const body = document.body;
const p1 = document.createElement("p");
p1.textContent = "In The Name Of Allah";
body.appendChild(p1);
const html = document.body;
const section = document.createElement("section");
html.appendChild(section);
const html1 = document.body;
const div = document.createElement("div");
section.appendChild(div);
const html2 = document.body;
const p = document.createElement("p1");
div.appendChild(p);
p.textContent = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus odit, dolore nihil velit iusto voluptatem sit fugiat facere ut qui repudiandae esse amet molestias, quidem nemo, maiores recusandae possimus ea! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa iste numquam doloremque aut quae minima qui, non possimus, eligendi consectetur necessitatibus natus, assumenda in exercitationem similique repellendus at voluptas magni!";
const html3 = document.body;
const button = document.createElement("button");
section.appendChild(button);
button.textContent="SEND";
